parameters:
  ServiceConnection:

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_image
    displayName: Build
    pool:
      name: DAS - Continuous Integration Agents
    steps:
    - template: azure-pipelines-templates/build/step/gitversion.yml@das-platform-building-blocks  
    - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
      parameters:
        ContainerRegistryName: $(PublicAcrName)
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ImageName: $(WebContainerImageName)
        WorkingDirectory: $(Build.SourcesDirectory)/src/SFA.DAS.SecureMessageService.Web/
    - template: azure-pipelines-templates/build/step/dockerfile-build.yml@das-platform-building-blocks
      parameters:
        ContainerRegistryName: $(PublicAcrName)
        ServiceConnection: ${{ parameters.ServiceConnection }}
        ImageName: $(ApiContainerImageName)
        WorkingDirectory: $(Build.SourcesDirectory)/src/SFA.DAS.SecureMessageService.Api/

