resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/0.4.63
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.0.6
    endpoint: SkillsFundingAgency

trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
      - manifests/*
      - pipeline-templates/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

variables:
- group: Release Management Resources
- name: KubectlVersion
  value: 1.23.8
- name: WebContainerImageName
  value: das-secure-message-service
- name: ApiContainerImageName
  value: das-secure-message-service-api

stages:
- template: pipeline-templates/stage/build.yml
  parameters:
    ServiceConnection: SFA-DIG-Prod-ARM

- stage: DeployTo_PREPROD
  displayName: DeployTo_PREPROD
  variables:
  - group: PreProd Management Resources
  - group: PREPROD Tools Service Shared
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: PREPROD
      KeyVaultName: $(SharedKeyVaultName)
      KubectlVersion: $(KubectlVersion)
      ServiceConnection: SFA-DIG-PreProd-ARM
      AksResourceGroup: $(AKSResourceGroupName)
      KubernetesCluster: $(AKSSharedClusterName)

- stage: DeployTo_PROD
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: DeployTo_PROD
  variables:
  - group: Prod Management Resources
  - group: PROD Tools Service Shared
  jobs:
  - template: pipeline-templates/job/deploy.yml
    parameters:
      AppGatewayName: $(AKSSharedAppGatewayName)
      AppGatewayResourceGroup: $(AKSSharedNodeResourceGroupName)
      Environment: PROD
      KeyVaultName: $(SharedKeyVaultName)
      KubectlVersion: $(KubectlVersion)
      ServiceConnection: SFA-DIG-Prod-ARM
      AksResourceGroup: $(AKSResourceGroupName)
      KubernetesCluster: $(AKSSharedClusterName)
