trigger:
- master

pool:
  name: 'Continuous Integration 02 - SSD - 160ACU'

variables:
  buildConfiguration: 'Release'
  solutionPath: '$(Build.SourcesDirectory)\src\SFA.DAS.SecureMessageService.sln'

steps:
- task: gittools.gitversion.gitversion-task.GitVersion@3

- script: |
    dotnet restore
    dotnet build $(solutionPath) --configuration $(buildConfiguration)
    dotnet publish $(solutionPath) --configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY

- task: PublishBuildArtifacts@1