trigger:
  batch: true
  branches:
    include:
      - "*"
  paths:
    include:
      - manifests/*
      - src/*
      - azure-pipelines.yml
      - Dockerfile

pr: none

variables:
  - group: 'Dev Management Resources'

pool:
    name: "DAS - Continuous Integration"

stages:
- stage: build
  displayName: Build
  jobs:
  - job: build_image
    displayName: Build
    steps:
      - task: UseGitVersion@5
        inputs:
          versionSpec: 5.x
          useConfigFile: true
          configFilePath: GitVersion.yml

      - task: Docker@2
        displayName: Build Base Image
        inputs:
            command: build
            dockerfile: docker/Build.Dockerfile
            repository: das-secure-message-service-build
            buildContext: .
            tags: latest

      - task: Docker@2
        displayName: Build Web Image
        inputs:
            command: build
            dockerfile: docker/Web.Dockerfile
            repository: apprenticeshipsdevops/das-secure-message-service
            buildContext: .
            tags: |
                $(Build.BuildNumber)
                $(build.BuildNumber)-production

      - task: Docker@2
        displayName: Build Api Image
        inputs:
            command: build
            dockerfile: docker/Api.Dockerfile
            repository: apprenticeshipsdevops/das-secure-message-service-api
            buildContext: .
            tags: |
                $(Build.BuildNumber)
                $(build.BuildNumber)-production

      - task: Docker@2
        displayName: Login to Docker Hub
        inputs:
            command: login
            containerRegistry: "Apprenticeships DevOps Docker Hub"

      - task: Docker@2
        displayName: Push Web Image
        inputs:
            command: push
            repository: apprenticeshipsdevops/das-secure-message-service
            tags: $(Build.BuildNumber)

      - task: Docker@2
        displayName: Push Web Image Latest if master
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
            command: push
            repository: apprenticeshipsdevops/das-secure-message-service
            tags: $(build.BuildNumber)-production

      - task: Docker@2
        displayName: Push Api Image
        inputs:
            command: push
            repository: apprenticeshipsdevops/das-secure-message-service-api
            tags: $(Build.BuildNumber)

      - task: Docker@2
        displayName: Push Api Image Latest if master
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
            command: push
            repository: apprenticeshipsdevops/das-secure-message-service-api
            tags: $(build.BuildNumber)-production

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          contents: |
            azure/**
            manifests/**
          targetFolder: '$(build.artifactstagingdirectory)/publish'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact'
        inputs:
          pathtoPublish: '$(build.artifactstagingdirectory)/publish'
