parameters:
  azureSubscription:
  aksResourceGroupName:
  aksClusterName:
  environment:
  variablegroupName:

jobs:
  - deployment: deploy_${{parameters.environment}}
    displayName: Deploy ${{parameters.environment}}
    environment: ${{parameters.environment}}

    variables:
      - group: ${{parameters.variablegroupName}}

    pool:
      name: 'DAS - Continuous Integration'

    strategy:
      runOnce:
        deploy:
          steps:
          - script: env
          - task: DownloadPipelineArtifact@2
            inputs:
              artifact: manifests
              path: $(system.defaultworkingdirectory)/manifests
          - task: replacetokens@3
            displayName: 'Tokenize Manifests'
            inputs:
              rootDirectory: $(Pipeline.Workspace)/manifests
              targetFiles: '*.yml'
              encoding: 'auto'
              writeBOM: true
              actionOnMissing: 'fail'
              keepToken: false
              tokenPrefix: '{{'
              tokenSuffix: '}}'
          - task: KubectlInstaller@0
            displayName: 'Install Kubectl latest'
          - task: Kubernetes@1
            displayName: 'Configure Deployment'
            inputs:
              connectionType: 'Azure Resource Manager'
              azureSubscriptionEndpoint: ${{parameters.azureSubscription}}
              azureResourceGroup: ${{parameters.aksResourceGroupName}}
              kubernetesCluster: ${{parameters.aksClusterName}}
              useClusterAdmin: true
              command: apply
              useConfigurationFile: true
              configuration: $(Pipeline.Workspace)/manifests/deployment.yml
