name: '0.1.0-$(Rev:r)'
trigger:
  batch: true
  branches:
    include:
      - master

workspace:
    clean: all

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  imageName: "sms:$(build.buildNumber)"
  solutionPath: '$(build.sourcesDirectory)/src/SFA.DAS.SecureMessageService.sln'

steps:

- script: |
    dotnet restore
    dotnet build $(solutionPath) --configuration $(buildConfiguration)
    dotnet publish $(solutionPath) --configuration $(buildConfiguration) --output $(build.sourcesDirectory)/src/release
  displayName: "Build app"    

- script: |
    docker build -f Dockerfile -t $(acrName).azurecr.io/$(imageName) .
    docker login -u $(acrName) -p $password $(acrName).azurecr.io
    docker push $(acrName).azurecr.io/$(imageName)
  displayName: "Build image"
  env:
    password: $(acrPassword)

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'Drop'
  enabled: false