parameters:
  AppGatewayName:
  AppGatewayResourceGroup:
  Environment:
  KeyVaultName:
  KubectlVersion:
  ServiceConnection:
  AksResourceGroup:
  KubernetesCluster:
jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  pool:
    name: DAS - Continuous Deployment
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: das-secure-message-service/
        - task: replacetokens@3
          displayName: Tokenise manifests
          inputs:
            rootDirectory: $(Pipeline.Workspace)/das-secure-message-service/manifests
            targetFiles: '**/*.yml'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: fail
            keepToken: false
            tokenPrefix: '{{'
            tokenSuffix: '}}'
            verbosity: detailed
        - task: KubectlInstaller@0
          displayName: Install Kubectl ${{ parameters.KubectlVersion }}
          inputs:
            kubectlVersion: ${{ parameters.KubectlVersion }}
        - template: azure-pipelines-templates/deploy/step/create-kubernetes-ingress.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.KubernetesCluster }}
            AksResourceGroupName: ${{ parameters.AksResourceGroup }}
            AppGatewayName: ${{ parameters.AppGatewayName }}
            AppGatewayResourceGroup: ${{ parameters.AppGatewayResourceGroup }}
            AzureServiceConnection: ${{ parameters.ServiceConnection }}
            IngressManifestPath: $(Pipeline.Workspace)/das-secure-message-service/manifests/web-ingress.yml
            KeyVaultName: ${{ parameters.KeyVaultName }}
            Namespace: engineering
        - template: azure-pipelines-templates/deploy/step/create-kubernetes-ingress.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.KubernetesCluster }}
            AksResourceGroupName: ${{ parameters.AksResourceGroup }}
            AppGatewayName: ${{ parameters.AppGatewayName }}
            AppGatewayResourceGroup: ${{ parameters.AppGatewayResourceGroup }}
            AzureServiceConnection: ${{ parameters.ServiceConnection }}
            IngressManifestPath: $(Pipeline.Workspace)/das-secure-message-service/manifests/api-ingress.yml
            KeyVaultName: ${{ parameters.KeyVaultName }}
            Namespace: engineering
        - task: Kubernetes@1
          displayName: Create Web Deployment
          inputs:
            connectionType: Azure Resource Manager
            azureSubscriptionEndpoint: ${{ parameters.ServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroup }}
            kubernetesCluster: ${{ parameters.KubernetesCluster }}
            namespace: engineering
            command: apply
            useConfigurationFile: true
            configuration: $(Pipeline.Workspace)/das-secure-message-service/manifests/web-deployment.yml
            useClusterAdmin: true
        - task: Kubernetes@1
          displayName: Create Api Deployment
          inputs:
            connectionType: Azure Resource Manager
            azureSubscriptionEndpoint: ${{ parameters.ServiceConnection }}
            azureResourceGroup: ${{ parameters.AksResourceGroup }}
            kubernetesCluster: ${{ parameters.KubernetesCluster }}
            namespace: engineering
            command: apply
            useConfigurationFile: true
            configuration: $(Pipeline.Workspace)/das-secure-message-service/manifests/api-deployment.yml
            useClusterAdmin: true
