---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: das-secure-message-service-api
  namespace: {{KubernetesNamespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /api/messages
        pathType: Exact
        backend:
          service:
            name: das-secure-message-service-api
            port:
              number: 80
      - path: /api/messages/*
        pathType: Prefix
        backend:
          service:
            name: das-secure-message-service-api
            port:
              number: 80
