---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: das-secure-message-service-api
  namespace: engineering
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /api/messages
        backend:
          serviceName: das-secure-message-service-api
          servicePort: 80
      - path: /api/messages/*
        backend:
          serviceName: das-secure-message-service-api
          servicePort: 80
