---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: das-secure-message-service-api
    service: das-tool-service
  name: das-secure-message-service-api
  namespace: {{KubernetesNamespace}}
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: das-secure-message-service-api
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: das-secure-message-service-api
    service: das-tool-service
  name: das-secure-message-service-api
  namespace: {{KubernetesNamespace}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: das-secure-message-service-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: das-secure-message-service-api
        service: das-tool-service
    spec:
      nodeSelector:
        agentpool: tools01
      containers:
      - env:
        - name: AzureAd__Tenant
          value: {{Tenant}}
        - name: AzureAd__Identifier
          value: {{SecureMessageServiceApiIdentifierUri}}
        image: {{PublicAcrName}}.azurecr.io/{{ApiContainerImageName}}:{{BuildNumber}}
        imagePullPolicy: IfNotPresent
        name: das-secure-message-service-api
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 25m
            memory: 512Mi
        envFrom:
          - configMapRef:
              name: das-tool-service-shared-config
        readinessProbe:
          httpGet:
            path: "/api/messages/health"
            port: 80
          periodSeconds: 10
          timeoutSeconds: 1
      volumes:
        - name: shared-app-settings
          configMap:
            name: das-tool-service-shared-config
