---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: das-secure-message-service-web
  namespace: {{KubernetesNamespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /messages
        backend:
          serviceName: das-secure-message-service-web
          servicePort: 80
      - path: /messages/*
        backend:
          serviceName: das-secure-message-service-web
          servicePort: 80
