---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: das-secure-message-service-web
  namespace: engineering
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/health-probe-path: "/messages/health"
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /messages/(.*)
        backend:
          serviceName: das-secure-message-service-web
          servicePort: 80
